### ISSUE TITLE
Standard default output should be a valid JSON array

### ISSUE THREAD

**Issue by simonw** [simonw/s3-credentials#48]
> I just spotted `list-buckets` has the same not-quite-newline-delimited JSON output format, which is a bad default. I should fix that too.

_Originally posted by @simonw in https://github.com/simonw/s3-credentials/issues> /28#issuecomment-1014838721_

**Comment by simonw** [comment]
The current documented display options are:

> Add `--nl` to collapse these to single lines as valid newline-delimited JSON.
> 
> Add `--array` to output a valid JSON array of objects instead.

Defaulting to pretty-printed invalid newline-delimited JSON was a weird design choice that I made!

```
% s3-credentials list-buckets
{
    "Name": "aws-cloudtrail-logs-462092780466-f2c900d3",
    "CreationDate": "2021-03-25 22:19:54+00:00"
}
{
    "Name": "simonw-test-bucket-for-s3-credentials",
    "CreationDate": "2021-11-03 21:46:12+00:00"
}
```
Fixing this would require a major version bump if I had hit 1.0 already.

**Comment by simonw** [comment]
In that case I think the safest default would be to turn the above into a pretty-printed streaming JSON array:
```
% s3-credentials list-buckets
[
  {
    "Name": "aws-cloudtrail-logs-462092780466-f2c900d3",
    "CreationDate": "2021-03-25 22:19:54+00:00"
  },
  {
    "Name": "simonw-test-bucket-for-s3-credentials",
    "CreationDate": "2021-11-03 21:46:12+00:00"
  }
]
```

**Comment by simonw** [comment]
Getting this right will mean I can pipe into `sqlite-utils insert` easily to create a SQLite database, which would be fun.

**Comment by simonw** [comment]
Here's how the current `list-buckets` implementation works:

https://github.com/simonw/s3-credentials/blob/aa690245e39ba2139ce9c0267ed34e61100037d8/s3_credentials/cli.py#L556-L564

I need a new abstraction I can call that knows how to turn an iterator of rows into one of the desired formats.

**Comment by simonw** [comment]
Most interesting new implementation here will be the code that knows how to output something like this in a streaming fashion, without buffering it all in an array first:
```json
[
  {
    "Name": "aws-cloudtrail-logs-462092780466-f2c900d3",
    "CreationDate": "2021-03-25 22:19:54+00:00"
  },
  {
    "Name": "aws-sam-cli-managed-default-samclisourcebucket-1ksajo4h62s07",
    "CreationDate": "2020-06-16 23:13:34+00:00"
  },
  {
    "Name": "blah-bucket-blah",
    "CreationDate": "2021-11-10 23:50:08+00:00"
  }
]
```
Trick will be to output `[` at the start, then two-space indented (with `textwrap`) `json.dumps(..., indent=2)` rows with commas after each except the last one - and then a `]` at the end.

**Comment by simonw** [comment]
Good code to imitate from `sqlite-utils`: https://github.com/simonw/sqlite-utils/blob/74586d3cb26fa3cc3412721985ecdc1864c2a31d/sqlite_utils/cli.py#L1589-L1623

**Comment by simonw** [comment]
Actually I probably want to use `csv.DictWriter` here:
```python
writer = csv.DictWriter(sys.stdout, headers)
dict_writer.writeheader()
dict_writer.writerows(iterator_of_dictionaries)
```

**Comment by simonw** [comment]
This outputs 2-indented JSON in a streaming fashion:
```python
def output_rows_json(iterator):
    # We have to iterate two-at-a-time so we can know if we
    # should output a trailing comma or if we have reached
    # the last row.
    current_iter, next_iter = itertools.tee(iterator, 2)
    next(next_iter, None)
    first = True
    for row, next_row in itertools.zip_longest(current_iter, next_iter):
        is_last = next_row is None
        data = row
        line = "{firstchar}{serialized}{maybecomma}{lastchar}".format(
            firstchar="[\n" if first else "",
            serialized=textwrap.indent(json.dumps(data, indent=2, default=repr), '  '),
            maybecomma="," if not is_last else "",
            lastchar="\n]" if is_last else "",
        )
        yield line
        first = False
    if first:
        # We didn't output any rows, so yield the empty list
        yield "[]"
```
Demo:
```
print("\n".join(output_rows_json([{"id": 1, "name": "Simon"}, {"id": 2, "name": "Cleo"}, {"id": 3, "name": "Azi"}])))

[
  {
    "id": 1,
    "name": "Simon"
  },
  {
    "id": 2,
    "name": "Cleo"
  },
  {
    "id": 3,
    "name": "Azi"
  }
]
```

**Comment by simonw** [comment]
Turned that into a TIL: https://til.simonwillison.net/python/output-json-array-streaming

**Comment by simonw** [comment]
Ran into a problem applying this to `list-users`:
```
% s3-credentials list-users --csv
Path,UserName,UserId,Arn,CreateDate
... many rows follow ...
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/s3-credentials-J8M1ChYK/bin/s3-credentials", line 33, in <module>
    sys.exit(load_entry_point('s3-credentials', 'console_scripts', 's3-credentials')())
  File "/Users/simon/.local/share/virtualenvs/s3-credentials-J8M1ChYK/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/share/virtualenvs/s3-credentials-J8M1ChYK/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/share/virtualenvs/s3-credentials-J8M1ChYK/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/share/virtualenvs/s3-credentials-J8M1ChYK/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/share/virtualenvs/s3-credentials-J8M1ChYK/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/Dropbox/Development/s3-credentials/s3_credentials/cli.py", line 495, in list_users
    output(iterate(), nl, csv, tsv)
  File "/Users/simon/Dropbox/Development/s3-credentials/s3_credentials/cli.py", line 789, in output
    writer.writerows(itertools.chain([first], iterator))
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/csv.py", line 157, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
  File "/Users/simon/.pyenv/versions/3.10.0/lib/python3.10/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'PasswordLastUsed'
```
CSV output failed because one of the later rows had a new unexpected column.

**Comment by simonw** [comment]
Options for fixing this:
- Silently ignore columns that were not in the first record. Easiest fix.
- For CSV mode load everything into memory first to check for the maximum set of headers. This breaks the goal of having this work efficiently with the streamed data.
- Figure out the full set of possible columns and hard-code that into the application. Probably the best solution?

**Comment by simonw** [comment]
I considered an option where it spots the error, runs to the end to capture all possible headers, then runs the entire command again - but that wouldn't work because we would already have outputted headers and previous rows to stdout.

**Comment by simonw** [comment]
I'm going to hard-code in the list of known columns. This also gives me control over the order in which they are output.

For `list-users` that's https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/iam.html#IAM.Client.list_users

- `Path`
- `UserName`
- `UserId`
- `Arn`
- `CreateDate`
- `PasswordLastUsed`
- `PermissionsBoundary`
- `Tags`

**Comment by simonw** [comment]
Fun trick with this:
```
% s3-credentials list-users --tsv | sqlite-utils memory stdin:tsv 'select * from stdin' -t
UserName                                               UserId                 Arn                                                                                   Path    CreateDate                 PasswordLastUsed           PermissionsBoundary    Tags
-----------------------------------------------------  ---------------------  ------------------------------------------------------------------------------------  ------  -------------------------  -------------------------  ---------------------  ------
custom-policy                                          AIDAWXFXAIOZNQQMEOHUA  arn:aws:iam::462092780466:user/custom-policy                                          /       2021-11-03 18:31:22+00:00
dogsheep-photos-simon-read                             AIDAWXFXAIOZKDDGOUY5H  arn:aws:iam::462092780466:user/dogsheep-photos-simon-read                             /       2020-04-18 19:56:54+00:00
dogsheep-photos-simon-read-write                       AIDAWXFXAIOZHYXFF3NA
```

**Comment by simonw** [comment]
OK, this is done for `list-users` and `list-buckets` and `list-bucket`.

`list-user-policies` doesn't output JSON at all, it has a weird custom output - so I'm leaving it for the moment.
