### ISSUE TITLE
`s3-credentials create name-of-bucket --create-bucket --public` fails with error

### ISSUE THREAD

**Issue by simonw** [simonw/s3-credentials#88]
```bash
s3-credentials create test-public-bucket-simonw --create-bucket --public
```
```
Created bucket: test-public-bucket-simonw
Traceback (most recent call last):
  File "/Users/simon/.local/bin/s3-credentials", line 8, in <module>
    sys.exit(cli())
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/s3_credentials/cli.py", line 406, in create
    s3.put_bucket_policy(
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/simon/.local/pipx/venvs/s3-credentials/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutBucketPolicy operation: Access Denied
```
Split from:
- #87

**Comment by simonw** [comment]
My best guess is that AWS changed something and now this code here:

https://github.com/simonw/s3-credentials/blob/6f46d5d97b828894eca4e9018e535ea796f87b68/s3_credentials/cli.py#L376-L378

https://github.com/simonw/s3-credentials/blob/6f46d5d97b828894eca4e9018e535ea796f87b68/s3_credentials/cli.py#L405-L409

Is failing because I should have run this first:

```python
s3.put_public_access_block(
    Bucket=bucket,
    PublicAccessBlockConfiguration={
        "BlockPublicAcls": False,
        "IgnorePublicAcls": False,
        "BlockPublicPolicy": False,
        "RestrictPublicBuckets": False,
    },
)
```

**Comment by simonw** [comment]
Here's what a `--dry-run` looks like now:
```bash
s3-credentials create simonw-test-public-access2 --create-bucket --public --dry-run
```
```
Would create bucket: 'simonw-test-public-access2'
... then this public access block configuration:
{"BlockPublicAcls": false, "IgnorePublicAcls": false, "BlockPublicPolicy": false, "RestrictPublicBuckets": false}
... then attach the following bucket policy to it:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowAllGetObject",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::simonw-test-public-access2/*"
            ]
        }
    ]
}
Would create user: 's3.read-write.simonw-test-public-access2' with permissions boundary: 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
Would attach policy called 's3.read-write.simonw-test-public-access2' to user 's3.read-write.simonw-test-public-access2', details:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": [
                "arn:aws:s3:::simonw-test-public-access2"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectLegalHold",
                "s3:GetObjectRetention",
                "s3:GetObjectTagging"
            ],
            "Resource": [
                "arn:aws:s3:::simonw-test-public-access2/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::simonw-test-public-access2/*"
            ]
        }
    ]
}
Would call create access key for user 's3.read-write.simonw-test-public-access2'
```

**Comment by simonw** [comment]
And `debug-bucket` against a bucket created with those options:
```bash
s3-credentials debug-bucket simonw-test-public-access2
```
```
Bucket ACL:
{
    "Owner": {
        "DisplayName": "swillison",
        "ID": "36b2eeee501c5952a8ac119f9e5212277a4c01eccfa8d6a9d670bba1e2d5f441"
    },
    "Grants": [
        {
            "Grantee": {
                "DisplayName": "swillison",
                "ID": "36b2eeee501c5952a8ac119f9e5212277a4c01eccfa8d6a9d670bba1e2d5f441",
                "Type": "CanonicalUser"
            },
            "Permission": "FULL_CONTROL"
        }
    ]
}
Bucket policy status:
{
    "PolicyStatus": {
        "IsPublic": true
    }
}
Bucket public access block:
{
    "PublicAccessBlockConfiguration": {
        "BlockPublicAcls": false,
        "IgnorePublicAcls": false,
        "BlockPublicPolicy": false,
        "RestrictPublicBuckets": false
    }
}
```

**Comment by simonw** [comment]
And uploading a file to it:
```bash
s3-credentials put-object \
  simonw-test-public-access2 chicken.png \
  ~/Desktop/Archive/black_and_white_spotted_chicken,_realistic_photo,_garden.png
```
Resulted in:

https://s3.amazonaws.com/simonw-test-public-access2/chicken.png

So this worked.
